# Generated by Django 5.2 on 2025-04-08 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_and_answer', '0002_remove_answer_created_on_answer_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_on',
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 9, 42, 54, 304821)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 9, 42, 54, 304821)),
        ),
    ]
