# Generated by Django 5.2 on 2025-04-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_and_answer', '0003_remove_question_created_on_question_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 16, 8, 5, 991087)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 16, 8, 5, 991087)),
        ),
    ]
